# Generated by Django 6.0.4 on 2026-04-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อวิดีโอ')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('category', models.CharField(choices=[('wedding', 'งานแต่งงาน'), ('event', 'งาน Event'), ('commercial', 'โฆษณา'), ('documentary', 'สารคดี'), ('music', 'MV เพลง'), ('other', 'อื่นๆ')], default='other', max_length=20, verbose_name='หมวดหมู่')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='ภาพปก')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='ไฟล์วิดีโอ')),
                ('youtube_url', models.URLField(blank=True, verbose_name='ลิงก์ YouTube (ถ้ามี)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='แนะนำ')),
                ('order', models.IntegerField(default=0, verbose_name='ลำดับ')),
            ],
            options={
                'verbose_name': 'วิดีโอ',
                'verbose_name_plural': 'วิดีโอทั้งหมด',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
